### ISSUE TITLE
Validate UI and Vai Cache against an enterprise environment

### ISSUE THREAD

**Issue by richard-cox** [rancher/qa-tasks#1848]
Blocked on
- ~https://github.com/rancher/dashboard/issues/12734~
- ~https://github.com/rancher/rancher/issues/40773~

The changes above bring in a way to automatically update resource lists when resources of that type change. This is a whole new process and requires thorough validation, specifically for enterprise like environments.

Those environments might start at

- Lots of resources
  - ~1000 deployments
- Lots of resource change churn
  - ~200 changes to pods a second
- Lots of tabs
  - multiple ui sessions open, given 1 tab per session
  - amount tbd, but low bar total 20(?) across all users
- Lots of users 
  - multiple users logged in
  - amount tbd, but low bar 10(?)
- HA
  - There should be at least three replicas (default, but just in case helm arg `--set replicas=3`)

The aim would be to visit the pods list and validate
- initial load time is reasonable
- page is continually responsive
- updates to resources are shown within 5 seconds of them happening

Updated test description
- At least 10 users logged in, all below admin
  - Admins have 1 kube socket open per resource per tab
  - Non-admins have 1 kube socket open per namespace per resource per tab
- Total of 20 tabs open (can be 1 user with 11 tabs, 9 users with 1 tab)
  - Users should be able to navigate through various resources in A cluster
  - Ideally downstream, ok if not 
- UI when user is on a Resource lists (in the cluster view) should be working correctly AND responsive
  - Initial load time is reasonable (<1 second)
  - Page is continuously response (no juddering, jagged / disjointed rendering)
  - Changes to resources in that list are shown every 5 seconds
    - This tests the new resource update process

If it helps, something like this can be used to create the churn

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crashing-test-pod{number}
spec:
  selector:
    matchLabels:
      app: crashing-test-pod{number}
  replicas: 10
  template:
    metadata:
      labels:
        app: crashing-test-pod{number}
    spec:     
      containers:
        - command:
            - bash
            - -c
            - "echo test; sleep 10; exit 1;"
          image: ubuntu
          name: crashing-test-container
```
