### ISSUE TITLE
Update Test Names to accurately represent what the user provides in the config file

### ISSUE THREAD

**Issue by slickwarren** [rancher/qa-tasks#863]
Currently, we don't have any way of tracking what is in the user config. This means that we lose a lot of information about what was actually tested when looking back on test runs / releases. 

i.e. node pools (for dynamic tests) and roles, any customization to the cluster i.e. clusterAgentOverride, etcd/snapshot schedule, registries, hardened, ... pretty much anything in the config that isn't explicitly added to the test name (which is currently nodeProvider, Kube Version, CNI, and user/client)

Currently, the suggestion would be to add anything that the user specifies in the config to the test's name. this would help post-release to have the ability to go back and see exactly what was or wasn't tested. 
So if my config has the following 
```
nodesAndRolesRKE1:
...
  - etcd: true
    controlplane: true
    worker: true
    quantity: 1
  providers: ["linode"]
  nodeProviders: ["ec2"]
  hardened: false
  basics:
    rke1KubernetesVersion: ["v1.25.11-rancher1-1"]
    cni: ["calico"] # ,"canal"

  etcd:
    snapshotRetention: 4
    snapshotScheduleCron: "*/5 * * * *"
  clusterAgent:
    appendTolerations:
    - key: Testkey
      value: testValue
      effect: NoSchedule
...
```
then the test name should look something like 
```
Standard_User_1Node(_Etcd__ControlPlane__Worker_)__Node_Provider:_linode_Kubernetes_version:_v1.25.11-rancher1-1_cni:_calico_SnapshotRetention:_4_SnapshotScheduleCron_*/5 * * * *_ClusterAgent:_AppendTolerations:TestKey:TestValue:NoSchedule
```
instead of just `Standard_User_Node_Provider:_linode_Kubernetes_version:_v1.25.11-rancher1-1_cni:_calico` as we currently have. 

Pros of proposed approach: would be more clear in a test report using Qase of what was tested, increasing visibility into what is tested and when

Cons:
* naming can become quite long and possibly not as user-friendly as we currently have it
  * Qase could help mitigate this with its nested Suite / Naming structure
* would still depend on the user to provide a correct and complete config file. If something is missed or left out of the config, then it won't be tested

Alternatives:
* instead of depending on the user, we could have something like what we have for ACE where there is a dedicated test per variable. This would guarantee testing of given variables on the cluster however, this presents more cons like not having visibility into combined configs (i.e. testing ACE + hardened cluster) without adding another dedicated test for it. Also it would be more work to do it this way vs. update naming
