### ISSUE TITLE
Update configuration input check in RKE2 ACE tests

### ISSUE THREAD

**Issue by caliskanugur** [rancher/qa-tasks#883]
In the RKE2 ACE tests, t[he configuration empty check](https://github.com/rancher/rancher/blob/release/v2.8/tests/v2/validation/provisioning/rke2/ace_test.go#L94) should be updated as a nil check. 

```
  networking: 
    localClusterAuthEndpoint:
      enabled: false
      fqdn: ''
      caCerts: ''
```

The above configuration input in testify's current version would be empty and non-nil.
